examples/android/enhanced_webview_streaming/app/src/main/assets/js/anbox-stream-sdk.js
Version 1 of the API was used by Anbox until 1.17.2, 10 months ago. That's out of standard support for a while.
This patch comes directly from our internal repository and was apparently missed when moving to GH.
=> feat(stream-sdk): remove API fallback mechanism

js/anbox-stream-sdk.js, js/tests/unit/input-events.test.js
With support for pointer lock we can support use cases where the mouse and relative motion information is used instead of absoluate coordinates, like in various games not using touch input but explicit mouse information. Support is kept behind a feature flag until we have stablized and tested the implementation further.
=> feat(js): add support for pointer lock in the SDK

js/anbox-stream-sdk.js
Added `vhalReady` callback to allow a consumer of the streaming SDK to be notified of the discovery of VHAL capabilities for the stream.
=> feat(stream-sdk): add vhalReady callback to notify of VHAL availability

.gitignore, js/tests/unit/run-tests.sh
- Added `.gitignore` file, so that artifacts created by the `scripts/run-tests.sh` script (`.npm` and `node_modules` folders) are ignored by git.
- Updated node version for the docker image where tests are run, from 17 (EOL since June 1st 2022) to 20 (latest LTS as of today).
=> chore: add .gitignore to skip artifacts, update node version for tests

.github/workflows/ci.yaml
Add `workflow_dispatch` event, which allows the CI workflow to enable people to select one specific branch without any inputs.
=> feat(.github): allow manual workflow_dispatch for a specific branch

js/anbox-stream-sdk.js
Added an optional flag to the `AnboxStream` options object to opt out of the default vertically centered alignment for the video element inside its container. For backward compatibility, it will be kept vertically centered by default, so that it doesn't interfere with previous usages by causing unexpected changes.
=> feat(video): allow to change default vertically centered video alignment

.github/workflows/e2e.yaml
We would previously checkout the canonical repo, but for a PR from a
fork we need to checkout the fork repo instead.
WD-12279
=> fix(ci) ensure a branch from a forked pr is available in ci

.github/workflows/e2e.yaml, js/tests/e2e/fixtures/constants.cjs, js/tests/e2e/global-setup.js, js/tests/e2e/global-teardown.js, js/tests/e2e/index.html, js/tests/e2e/playwright.config.js, js/tests/e2e/server.js, js/tests/e2e/tests/join.spec.js, js/tests/e2e/tests/shared.js, js/tests/e2e/tests/vhal.spec.js
- Determine architecture automatically by querying the `/nodes` endpoint of AMS.
- Add e2e tests for stream disconnect + `done` callback.
- Add e2e tests for VHAL: `vhalReady` callback, `getAllVhalPropConfigs`, `getVhalProperties`, `setVhalProperties` methods.
Until #37 is merged, you can see the test passing [here](https://github.com/lorumic/anbox-streaming-sdk/actions/runs/9676912820/job/26697489529).
Fixes [WD-11812](https://warthogs.atlassian.net/browse/WD-11812)
[WD-11812]: https://warthogs.atlassian.net/browse/WD-11812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(e2e): add e2e tests for stream disconnect, vhal methods [WD-11812]

.github/workflows/e2e.yaml
Replaced microbox with anbox-cloud-appliance for the execution of the e2e tests.
=> fix(e2e): use edge anbox-cloud-appliance instead of microbox

.github/workflows/cache-images.yaml, .github/workflows/e2e.yaml
We had to do quite a dance to get tests working as the e2e test workflow requires access to the Ubuntu Pro secret. We need to be careful to not allow access to it on a PR from a fork. The approach so far by using the pull_request_target trigger and a dedicated deployment environment with approval was working but far from perfect.
This now implements an alternative which does not require the direct use of the Ubuntu Pro token in the test workflow. Instead we use it to cache images in an independent workflow. The workflow will download all needed images and store them in the Github Action cache under a well known key name. When the e2e workflow now runs it will fetch the images from the cache and load into AMS. The workflow runs every day so we keep the images fresh.
-----
**NOTE** As the …
=> feat(gh): drop secret use from e2e workflow

.github/renovate.json
This matches what we implement elsewhere, specifically it pins actions now to specific digests rather than tags.
=> feat(gh): update renovate configration

js/anbox-stream-sdk.js, js/tests/unit/sdk.test.js
- Rotate the canvas rather than video element when upscaling is enabled
- Avoid a busy loop after stopping the streaming when upscaling is enabled
=> Fix the canvas rotation and avoid a busy loop after stopping the streaming when upscaling is enabled

js/anbox-stream-sdk.js, js/tests/unit/sdk.test.js
- fix(js-sdk): rotate the canvas rather than video element when upscaling is enabled
- fix(js-sdk): avoid a busy loop even after stopping the streaming
- fix(js-sdk): cancel video frame callback when video stream stops
=> [Backport] Fix the canvas rotation and avoid a busy loop after stopping the streaming when upscaling is enabled

js/anbox-stream-sdk.js
From the SDK API perspective, the JS SDK supports loading and executing
a single-pass shader for post-processing. However, a few more upscaling
solution is implmented based on multiple passes to achieve a better
result for real-time video streaming processing.
[Anime4K](https://github.com/bloc97/Anime4K) is an example.
With this change, the post-processing procedure can involve multiple
filter passes, allowing users to provide multiple fragment shaders.
Instead of applying a single shader to the texture read from the video
element:
video texture -> shader -> canvas
The video texture is rendered to a texture attached to a framebuffer
with applied shaders. The process involves swapping textures and
rendering onto another texture until the final filter pass, which is
then applied and …
=> feat(sdk): support multi-pass shaders for the scaling feature

.github/workflows/pr.yaml, examples/js/Dockerfile, examples/js/example.html, examples/js/run.sh, examples/js/sgsr.html, js/anbox-stream-sdk.js, scripts/streaming-sdk-files.allowlist
Snapdragon™ Game Super Resolution(SGSR), which integrates upscaling
and sharpening in one single GPU shader pass. The algorithm uses a
12-tap Lanczos-like scaling filter and adaptive sharpening filter,
which presents smooth images and sharp edges. For more details:
https://github.com/SnapdragonStudios/snapdragon-gsr
This change adds and integrates SGSR, this single GPU shader pass
into the streaming js sdk, and usd by default for the time being.
NOTE: for now, FSR is still kept in the source for reference.
In the end, we will choose the best upscaling algorithm from all
available options after benchmarking and comparing performance and
quality, and only ship the best one in the streaming SDK.
=> Add and integrate Snapdragon Game Super Resolution(SGSR) into js sdk

js/tests/e2e/tests/vhal.spec.js
- Temporarily removed e2e test for the `AP_POWER_STATE_REPORT` VHAL prop.
- Added e2e test for the `WHEEL_TICK` VHAL prop.
=> fix(e2e): do not test AP_POWER_STATE_REPORT VHAL prop temporarily

js/tests/e2e/tests/vhal.spec.js
Added back the e2e test for the `AP_POWER_STATE_REPORT` VHAL prop, following an image update.
=> fix(e2e): add back the `AP_POWER_STATE_REPORT` to VHAL e2e tests

js/tests/e2e/tests/visual.spec.js
Added a 1s timeout after text input and before checking the snapshot, to reduce the flakiness of the keyboard input visual test.
=> fix(e2e): add small delay between text input and snapshot check

README.md
Added instructions to the README of the repo, to explain how to run unit tests and end-to-end tests.
=> fix(readme): add instructions to run unit and e2e tests

js/tests/e2e/global-setup.js, js/tests/e2e/package.json, js/tests/e2e/server.js
Fix for the failure in the "Run code quality scan" job run [here](https://github.com/canonical/anbox-streaming-sdk/actions/runs/12274448590/job/34247382351).
We are getting unexpected search results when testing the visual output of sending keyboard input to the stream (see screenshots below). It should be possible to prevent that by putting the Android instance offline.
- Expected:
- Received:
=> fix(e2e): set session offline to avoid results in search widget

.github/workflows/tics.yaml, js/tests/e2e/global-setup.js, js/tests/e2e/package-lock.json, js/tests/e2e/package.json, js/tests/e2e/server.js
- Reverted the addition of an `execCommand` endpoint to reduce CodeQL warnings.
- Set rate limits to reduce CodeQL warnings.
- Use GH runners instead of self-hosted ones for the TICS workflow.
=> Fix TICS report workflow, revert `execCommand` addition, set rate limits

js/anbox-stream-sdk.js
- Added a check before the initialisation of a `_gamepadEventManager` instance. If it was already initialised before, it should `stopPolling` before initialising a new one, to avoid receiving redundant gamepad events.
=> fix(gamepad): stop polling in game manager to avoid redundant events

js/anbox-stream-sdk.js
Fixed TICS warning: expected 0 arguments but received 2, violating JSC_WRONG_NUMBER_OF_PARAMS.
Fixes #[WD-17751](https://warthogs.atlassian.net/browse/WD-17751)
[WD-17751]: https://warthogs.atlassian.net/browse/WD-17751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: resolve TICS compiler warning in _onError

js/anbox-stream-sdk.js
- Fixed TICS warning: Property 'error' does not exist on type 'Event', violating JSC_INEXISTENT_PROPERTY.
Fixes #[WD-17751](https://warthogs.atlassian.net/browse/WD-17751)
[WD-17751]: https://warthogs.atlassian.net/browse/WD-17751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: resolve TICS inexistent property warning

js/anbox-stream-sdk.js
- Fixes multiple compiler warnings violating the rule JSC_WRONG_NUMBER_OF_PARAMS 
- Fixes a single occurrence of the JSC_INEXISTENT_PROPERTY violation
Fixes #[WD-17751](https://warthogs.atlassian.net/browse/WD-17751)
[WD-17751]: https://warthogs.atlassian.net/browse/WD-17751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: TICS wrong number of params compiler warnings

js/anbox-stream-sdk.js, js/tests/unit/sdk.test.js, scripts/run-tests.sh
If a client accidentally enables the camera while their device is
not equipped with one, it triggers the `ANBOX_STREAM_SDK_ERROR_USER_MEDIA`
error. However, this is not a fatal error and make less sense to
abort the streaming when no camera is found.
In such cases, we simply report the error to the end user and
prevent the streaming SDK from handling it.
Run added unit test
AC-3082
https://bugs.launchpad.net/anbox-cloud/+bug/2077598
Does this impact the team's internal or public documentation? If yes, has the relevant documentation been updated?
=> Do not abort streaming on non-fatal errors

.github/workflows/release.yaml
Small changes to the release workflow: instead of tagging, and then creating the release and testing, we instead depend first build and test before tagging. We're thus not using the version generation script anymore, and instead rely on the tag name. In practice, this shouldn't change anything: if we're based on a tag, the generation script just returns the tag name.
This should avoid creating a tag, and then failing to publish the release as the tests or build failed (for instance).
Also add a way to specify a different commit than the branch head. This should give more flexibility in choosing the commit for the release, to ensure it is the aligned with the one used by the dashboard (as this is the version that was tested the most).
Last, this fills the body of the release with a link to …
=> Release workflow changes

js/anbox-stream-sdk.js, js/tests/unit/sdk.test.js
With the introduction of the verticalAlignment setting, the video's top 
offset should be adjusted accordingly. Otherwise, input event positions
may be misaligned.
Fixes https://bugs.launchpad.net/anbox-cloud/+bug/2093904
=> Respect verticalAlignment setting for video top offset

js/anbox-stream-sdk.js, js/tests/unit/sdk.test.js, scripts/run-tests.sh
This change backports the commits from the following PRs to stable-1.25 branch
https://github.com/canonical/anbox-streaming-sdk/pull/118
https://github.com/canonical/anbox-streaming-sdk/pull/123
[Steps for how to test the changes]
Fixes #
Does this impact the team's internal or public documentation? If yes, has the relevant documentation been updated?
=> Manual backport to stable-1.25 branch

.github/renovate.json
To decrease the amount of dependency update PRs we get from renovate, tell it to group digest updates together (e.g. GitHub actions).
Also add full semver information to GH digests, see https://github.com/renovatebot/renovate/discussions/21901.
Check next renovate run.
N/A
N/A
=> Group digest updates together in renovate

.github/workflows/pr.yaml
We should never reference a branch or tag but an explicit git sha266 rev.
n/a
n/a
n/a
=> chore: pin anbox-cloud-github-action to git rev

.github/workflows/tics.yaml
There is now a secret present at the org level named TICSAUTHTOKEN so we no longer need to have our own.
Run TICS workflow once merged
https://warthogs.atlassian.net/browse/AC-3245
n/a
=> chore: use global TICSAUTHTOKEN

.github/workflows/tics.yaml
- Use TICS artifact on self-hosted runner instead of github actions 
Fixes #[WD-20991](https://warthogs.atlassian.net/browse/WD-20991)
[WD-20991]: https://warthogs.atlassian.net/browse/WD-20991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: use tics on self-hosted runners

.github/workflows/branch.yaml
* This change allows the branching workflow to use github token to open a pull request on the repository itself.
=> fix(gh): add pull-requests write permission to branching workflow

.github/workflows/release.yaml
Checkout the whole history of the repository to ensure the generate version script works as intended - 1.26 backport.
Run Publish SDK workflow.
N/A
N/A
=> 1.26 - Checkout whole history to generate version correctly

.github/workflows/release.yaml
Add stable environment to publish SDK and fix commitish selection.
Run Publish SDK
N/A
N/A
=> 1.26 - Fix publish v2

js/tests/e2e/server.js
Update the minimum disk size in e2e tests to 4GB, following a change in AMS.
Run e2e tests.
N/A
N/A
=> Update disk size in e2e tests

js/tests/e2e/server.js
We are reverting to using ZFS by default, so we should go back to a 3GB default disk size.
Note: this PR will fail until we get a new AMS version.
Run e2e tests.
Contributes to [AC-3511](https://warthogs.atlassian.net/browse/AC-3511)
N/A
[AC-3511]: https://warthogs.atlassian.net/browse/AC-3511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "fix(e2e): update minimum disk size to 4GB"

.github/workflows/branch.yaml
The streaming SDK stable branch must match the commit actually used by the dashboard in the AMS repo.
As we may quickly diverge, we need to be able to branch from a given commit (the on in the stable branch in the AMS repo).
Run branching workflow.
N/A
N/A
=> Allow branching from given commit
